const configs = [
  {
    type: 'cash_in',
    percents: 0.03,
    max: {amount: 5, currency: 'EUR'},
  },
  {
    type: 'cash_out_juridical',
    percents: 0.3,
    min: {amount: 0.5, currency: 'EUR'},
  },
  {
    type: 'cash_out_natural',
    percents: 0.3,
    week_limit: {amount: 1000, currency: 'EUR'},
  },
];

const transitionList = [
  {
    date: '2016-01-05',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_in',
    operation: {amount: 200.0, currency: 'EUR'},
    result: 5.999999999999999,
  },
  {
    date: '2016-01-05',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_in',
    operation: {amount: 0, currency: 'EUR'},
    result: 0,
  },
  {
    date: '2016-01-06',
    user_id: 2,
    user_type: 'juridical',
    type: 'cash_out',
    operation: {amount: 300.0, currency: 'EUR'},
    result: 90,
  },
  {
    date: '2016-01-06',
    user_id: 2,
    user_type: 'juridical',
    type: 'cash_out',
    operation: {amount: 0, currency: 'EUR'},
    result: 50,
  },
  {
    date: '2016-01-06',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 30000, currency: 'EUR'},
    result: 8700,
  },
  {
    date: '2016-01-06',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 0, currency: 'EUR'},
    result: 0,
  },
  {
    date: '2016-01-07',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 1000.0, currency: 'EUR'},
    result: 300,
  },
  {
    date: '2016-01-07',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 100.0, currency: 'EUR'},
    result: 30,
  },
  {
    date: '2016-01-10',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 100.0, currency: 'EUR'},
    result: 30,
  },
  {
    date: '2016-01-10',
    user_id: 2,
    user_type: 'juridical',
    type: 'cash_in',
    operation: {amount: 1000000.0, currency: 'EUR'},
    result: 500,
  },
  {
    date: '2016-01-10',
    user_id: 3,
    user_type: 'natural',
    operation: {amount: 1000.0, currency: 'EUR'},
    result: 'Transaction type not match',
  },
  {
    date: '2016-01-10',
    user_id: 3,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 1000.0, currency: 'EUR'},
    result: 0,
  },
  {
    date: '2016-02-15',
    user_id: 4,
    user_type: 'natural',
    type: 'cash_out',
    operation: {amount: 300.0, currency: 'EUR'},
    result: 0,
  },
  {
    date: '2016-02-15',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_out',
    result: 'Transaction incomplete',
  },
  {
    date: '2016-02-15',
    user_id: 1,
    user_type: 'natural',
    type: 'cash_in',
    operation: {currency: 'EUR'},
    result: 'Transaction incomplete',
  },
  {
    date: '2016-02-15',
    user_id: 1,
    user_type: 'juridical',
    type: 'cash_out',
    operation: {currency: 'EUR'},
    result: 'Transaction incomplete',
  },
  {
    date: '2016-02-15',
    user_id: 1,
    user_type: 'juridical',
    type: 'cash_out',
    operation: {amount: 0.0, currency: 'EUR'},
    result: 50,
  },
  {
    date: '2016-02-15',
    user_id: 1,
    user_type: 'juridical',
    type: 'cash_out',
    operation: {amount: 100.0, currency: 'EUR'},
    result: 50,
  },
];

module.exports = {
  configs,
  transitionList,
};
